### ISSUE TITLE
Libraries definitions in eduerp.make

### ISSUE THREAD

**Issue by ibsoman** [eduerp/eduerp#1]
Hi,
While installing eduerp with drush make eduerp.make, fpdf_tpl folder is empty after processus compeltion.
Also, libraries[tcpdf][download][url] is not correct. I´ve had to download it manualy.

**Comment by takinbo** [comment]
Thanks @ibsoman for reporting this issue. Can you provide more details on the error you're receiving when installing EduERP? That will help in pinpointing the problem.

**Comment by ibsoman** [comment]
Hi @takinbo 
1- For tcpdf the drush make processus give ERROR while arriving to it (it´s the last library to download), but all other downloads give OK. And so, no directory is created for the other modules an libraries as there´s an error with the make process. After I verified I see that the url in the file eduerp.make is wrong. Just try by your self please. In a browser you´ll be redirected to the download page. I work it around by downloading manually.
2- For fpdf_tpl library I have no error. Just after the process completed, the folder sites/all/libraries/fpdf_tpl is created but empty. I again worked it around by manually downloading. I think this library is not mandatory for the install process.

**Comment by takinbo** [comment]
Thanks for the feedback. I'm going to leave this issue open until this gets resolved.

**Comment by kodion** [comment]
@ibsoman There is an updated version of tcpdf.  Make file has been updated and tested.
