### ISSUE TITLE
Modify register form

### ISSUE THREAD

**Issue by ibsoman** [eduerp/eduerp#12]
Hi all,
I could not post an issue in eduerp-fr, so I will post it here.
I would like to modify the register form by removing some fields (Ex: Religion, Permanent Address State, JAMB No., Health Status) and adding some others.
Is it possible? How to do it?

**Comment by alanbarrett** [comment]
You can edit the registration form by editing the 'profile' and 'student_profile' content types (accessible from the admin menus).

However it would be good to ask me before deleting a field, whether it is critical for functionality of EduERP. In particular, do not delete the JAMB No. field. It is the field used to find new registrations for clearance and is displayed/used in quite a few places. You could change the display name of the field to something more suitable for you, but I do not think it would be advisable to delete it... you will likely have serious problems.

```
Alan.
```

**Comment by kodion** [comment]
You can also hide these fields so they do not display in the form. Do this at /admin/content/node-type/student-profile/profile in the "User Registration" fieldset.    Only non-mandatory fields are listed so you will need to toggle the "required" checkbox in the "Global Settings" for the fields you are interested in at /admin/content/node-type/student-profile/fields.    You can add fields there too.

**Comment by ibsoman** [comment]
Thanks for the informations.
