### ISSUE TITLE
Staff list Name not displaying

### ISSUE THREAD

**Issue by delacosta456** [eduerp/eduerp#13]
Hi 
I am trying to add a field to display the staff list name but couldn't  .. in attach file a picture or name not displaying ..
![eduerp_errror_case](https://f.cloud.github.com/assets/1848734/2192684/8ea03692-986c-11e3-887e-13f3a189df70.png)

**Comment by alanbarrett** [comment]
When you created the staff user at
http://yoursite/admin/user/user/createyou should of had an area on the
form called "Personal Information" where
you enter the new staff member's name along with much more information. Do
you have this area on the form?

The user must also be given the "Staff" role on that page (but no others)
before submitting.

These users should automatically be listed with their names on the screen
you showed in the screenshot.

```
Alan.
```

**Comment by delacosta456** [comment]
Hi
I followed correctly the process for creating the user and assigning  only
the the staff role but once user created I could see in
http://yoursite/admin/user/user/createyou  Personal information. And
drupal's authenticated user's role is automatically assigned ( don't thinks
this could be causing problem).

Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 09:15
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

When you created the staff user at
http://yoursite/admin/user/user/createyou should of had an area on the
form called "Personal Information" where
you enter the new staff member's name along with much more information. Do
you have this area on the form?

The user must also be given the "Staff" role on that page (but no others)
before submitting.

These users should automatically be listed with their names on the screen
you showed in the screenshot.

 Alan.

On 18 February 2014 07:16, delacosta456 notifications@github.com wrote:

> Hi
> I am trying to add a field to display the staff list name but couldn't ..
> in attach file a picture or name not displaying ..
> [image: 
> eduerp_errror_case]<https://f.cloud.github.com/assets/1848734/2192684/8ea03692-9
> 86c-11e3-887e-13f3a189df70.png>
> 
> ## 
> 
> Reply to this email directly or view it on
> GitHubhttps://github.com/eduerp/eduerp/issues/13
> .

‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35361553 .

**Comment by alanbarrett** [comment]
Since you say you can see "Personal Information" on the create form could you go to http://yoursite/admin/user/user and find the staff user and click on that user and then take a screenshot of that user page so I can see what is there?

The profile there should show the user's names.

```
Alan.
```

**Comment by delacosta456** [comment]
Hi

Sorry it's a mistake I was writing I can't see  "Personal Information"..
Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 10:24
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

Since you say you can see "Personal Information" on the create form could
you go to http://yoursite/admin/user/user and find the staff user and click
on that user and then take a screenshot of that user page so I can see what
is there?

The profile there should show the user's names.
Alan.
‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35366034 .

**Comment by alanbarrett** [comment]
Can you access the database... is so please go to database and issue this query and tell me the results: SELECT \* FROM variable WHERE name='content_profile_profile';

It should be like this:
a:8:{s:6:"weight";s:1:"0";s:12:"user_display";s:4:"full";s:9:"edit_link";i:0;s:8:"edit_tab";s:3:"sub";s:8:"add_link";i:1;s:16:"registration_use";i:1;s:21:"admin_user_create_use";i:1;s:17:"registration_hide";a:0:{}}

I am worried that you do not have a good install.

```
Alan.
```

**Comment by delacosta456** [comment]
Hi alan

Here is the result of the query .

Result: 
a:8:{s:6:"weight";s:1:"0";s:12:"user_display";s:4:"full";s:9:"edit_link";i:0
;s:8:"edit_tab";s:3:"sub";s:8:"add_link";i:1;s:16:"registration_use";i:1;s:2
1:"admin_user_create_use";i:1;s:17:"registration_hide";a:0:{}}
Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 10:45
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

SELECT \* FROM variable WHERE name='content_profile_profile';

**Comment by delacosta456** [comment]
On question I am using the correct distro for productionŠ this is the one I
download  here http://demo.eduerp.org.ng/eduerp.tar.gz
Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 10:45
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

Can you access the database... is so please go to database and issue this
query and tell me the results: SELECT \* FROM variable WHERE
name='content_profile_profile';

It should be like this:
a:8:{s:6:"weight";s:1:"0";s:12:"user_display";s:4:"full";s:9:"edit_link";i:0
;s:8:"edit_tab";s:3:"sub";s:8:"add_link";i:1;s:16:"registration_use";i:1;s:2
1:"admin_user_create_use";i:1;s:17:"registration_hide";a:0:{}}

I am worried that you do not have a good install.
Alan.
‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35367625 .

**Comment by alanbarrett** [comment]
The SQL query you sent back seems good.

Please also try (and send results back to me)...
select \* from variable where name IN ('content_profile_use_profile', 'node_options_profile', 'ant_profile');

Omo may want to comment on suitability of http://demo.eduerp.org.ng/eduerp.tar.gz I am not sure.

The proper instructions to follow are at: http://eduerp.org.ng/download or https://github.com/eduerp/install

```
Alan.
```

**Comment by delacosta456** [comment]
Hi

Thanks .. For that query I get No record result .. ( have a look on attached
file)

About " The proper instructions to follow are at:
http://eduerp.org.ng/download or https://github.com/eduerp/install "  from
mac osx drush on pear chanel is deprecated so it's very difficult to use.
The virtualize version eduerp.ova   link is not working
Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 13:10
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

The SQL query you sent back seems good.

Please also try (and send results back to me)...
select \* from variable where name IN ('content_profile_use_profile',
'node_options_profile', 'ant_profile');

Omo may want to comment on suitability of
http://demo.eduerp.org.ng/eduerp.tar.gz I am not sure.

The proper instructions to follow are at: http://eduerp.org.ng/download or
https://github.com/eduerp/install
Alan.
‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35377960 .

**Comment by delacosta456** [comment]
Hi 
Finally got a working version of drush

But installing always auto cancel after saying yes Š

See in scenario in attach
Merci
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 13:10
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

The SQL query you sent back seems good.

Please also try (and send results back to me)...
select \* from variable where name IN ('content_profile_use_profile',
'node_options_profile', 'ant_profile');

Omo may want to comment on suitability of
http://demo.eduerp.org.ng/eduerp.tar.gz I am not sure.

The proper instructions to follow are at: http://eduerp.org.ng/download or
https://github.com/eduerp/install
Alan.
‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35377960 .

**Comment by alanbarrett** [comment]
I would like Omo to comment on your issues with install/drush.

I did not see any files attached to your postings.

The fact that you get no output from the SQL query indicates, I think, that install did not run correctly.

It is possible to run manually, but would be very difficult. I think it would be best if Omo Oaiya commented on the best approach. I have only run install on Linux Ubuntu. I do not think anyone has installed on OSX, but maybe someone can comment.

```
Alan.
```

**Comment by delacosta456** [comment]
Hi

Ok.. But another possibility could have be uploading to an dropbox or any
other sharing system a simple zip file of working distro ( *.zip ) for
download.
Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 17:30
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

I would like Omo to comment on your issues with install/drush.

I did not see any files attached to your postings.

The fact that you get no output from the SQL query indicates, I think, that
install did not run correctly.

It is possible to run manually, but would be very difficult. I think it
would be best if Omo Oaiya commented on the best approach. I have only run
install on Linux Ubuntu. I do not think anyone has installed on OSX, but
maybe someone can comment.
Alan.
‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35402462 .

**Comment by alanbarrett** [comment]
Even when you have got good code downloaded... the install still needs to run to correctly configure the database.

```
Alan.
```

**Comment by delacosta456** [comment]
Hi dear 
Year surly .. But the real problem is note getting a good code downloaded
( no good code in the demo downloaded , and not fully downloadable with
drush on mac) .
Merci
-----------------------\\\\\\\\\\\\\\\\
\
Serge ZOUMENOU 
Tel : +229 -- 66 599 738 / 98 761 333
Analyste Programmeur, Administrateur base de données
 Webmaster
Administrateur Réseaux (Câblage Interconnexion)
Administrateur Plateformes Réseaux Intranet-Extranet
Intégrateurs solutions archivage numérique.

-----------------------\\\\\\\\\\\\\\\\\

De :  Alan Barrett notifications@github.com
Répondre à :  eduerp/eduerp
<reply+i-27774094-9d761540d0b387b54197fe7c6f845ede4ae79eea-1848734@reply.git
hub.com>
Date :  mardi 18 février 2014 18:40
À :  eduerp/eduerp eduerp@noreply.github.com
Cc :  Serge ZOUMENOU sergiozoumenou@outlook.com
Objet :  Re: [eduerp] Staff list Name not displaying (#13)

Even when you have got good code downloaded... the install still needs to
run to correctly configure the database.
Alan.
‹
Reply to this email directly or view it on GitHub
https://github.com/eduerp/eduerp/issues/13#issuecomment-35411138 .

**Comment by kodion** [comment]
@delacosta456 -  please use the mailing list for your installation problems.

**Comment by delacosta456** [comment]
hi

Am i mis configuring something  cause the Name still not display an even in registration step only username and password are field displayed ...
