### ISSUE TITLE
Unable to determine mime type of spyc.php

### ISSUE THREAD

**Issue by viashimat** [eduerp/eduerp#2]
I am running OpenSUSE 12.3. I've installed the requisite software (Apache, Mysql, Postgresql, Drush, Git, and PHP). After running the: "drush make eduerp.make" command, I get the following error:

unable to determine mime type of spyc.php.

I'm running Drush version 5.8

**Comment by kodion** [comment]
Not familiar with this error.   Can you try using Drush from the pear channel and feedback? - http://drupal.org/project/drush

**Comment by terikon** [comment]
Try to enable fileinfo extension in php.ini :

extension=php_fileinfo.so

**Comment by komputa** [comment]
Have you enabled php-gd?

I got the same error when I failed to enable gd extension.

I am using ubuntu 12.04 though

**Comment by komputa** [comment]
Emmanuel Joseph sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/1a25d40a-e692-4ded-aa86-3ee903d067ad

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Unsubscribe: https://twitter.com/i/o?t=1&iid=92d2c54899cd46c4bb814cd8225e74ce&uid=0&c=IuVwbCB3dgFJ3Hwvtw0huTKh%2FG3hfodFN8PmGdwQIKWHyOhk4viFAgIXC37%2Fy3AkDW6KOVX2yPjhxFDkN2JSKitCHXmxalxdZOQX2rn30v0HqxCwoi9URQ%3D%3D&nid=9+26

Need help?
https://support.twitter.com
