### ISSUE TITLE
Account Input Text Field Validation

### ISSUE THREAD

**Issue by mbube2** [eduerp/eduerp#24]
I want to add reg validation for some field like Middile Name not accept Abbreviated name, I need help.  My university operates eduerp on drupal 6

**Comment by alanbarrett** [comment]
If you look in student.module, you will see there are already some checks on middle name, you could add more in the 'validate' part for 'profile'...
function student_nodeapi(&$node, $op, $a3=null, $a4=null) {
  if ($node->type == 'profile') {
    if ($op == 'validate') {
      $text = $node->field_profile_last_name[0]['value'];
      if (str_replace('&', '&amp;', $text) != htmlspecialchars($text, ENT_COMPAT, 'UTF-8')) { // Also validates UTF-8
        form_set_error('field_profile_last_name', 'double quote, less than or greater than characters are not allowed');
      }
      if (!empty($text) && !preg_match('/^[A-Z]/', $text)) {
        form_set_error('field_profile_last_name', 'First letter must be in Upper case, rest in lower case. Example John');
      }

      $text = $node->field_profile_middle_name[0]['value'];
      if (!empty($text)) {
        if (str_replace('&', '&amp;', $text) != htmlspecialchars($text, ENT_COMPAT, 'UTF-8')) { // Also validates UTF-8
          form_set_error('field_profile_middle_name', 'double quote, less than or greater than characters are not allowed');
        }
      }

    Alan.
