### ISSUE TITLE
Issue of installing git on server before installing eduerp

### ISSUE THREAD

**Issue by yemaj** [eduerp/eduerp#4]
Kindly help look into the issue of installing git on the server before one can complete eduerp installation.

Thank you.

**Comment by alanbarrett** [comment]
What operating system are you using?

The general instructions are here: https://help.github.com/articles/set-up-git

```
Alan.
```

**Comment by komputa** [comment]
I don't seem to find an instruction on how to install eduerp on a live web host. 
Please can you help me with that?

**Comment by kodion** [comment]
The tracker is for managing and fixing issues.  Please use the eduerp-users mailing list for general support  - http://lists.eko-konnect.org.ng/mailman/listinfo/eduerp-users
