### ISSUE TITLE
Unable to clone editablefields.git and eduerp.git

### ISSUE THREAD

**Issue by komputa** [eduerp/eduerp#5]
When running rush make eduerp.make

I encountered error:

editablefields.git and eduerp.git

Please what do I do to correct this?

**Comment by kodion** [comment]
@komputa 

I can't reproduce your issue.  You might have had connectivity issues to github

> > editablefields cloned from https://github.com/eduerp/editablefields.git.                                                                                             [ok]
> > eduerp cloned from https://github.com/eduerp/eduerp.git.                                                                                                             [ok]

Try again and feedback

**Comment by komputa** [comment]
Thank you Mr. Omoiya,

The Git installation on the apache2 was not properly done.

The issue was corrected immediately I reinstalled current git.

The challenge that I have now is that the program freeze my mysql.

I get the attached error and after some few clicks, it will take my mysql
down (and the site will go offline) which I have to restart (service
apache2 restart > service mysql start) before it will come up again.

(At that point all websites using the same mysql installation on the server
will now be able to connect to it

I dont know how to correct this.

Great job there sir.

Regards

On Sat, Aug 10, 2013 at 5:13 PM, Omo Oaiya notifications@github.com wrote:

> @komputa https://github.com/komputa
> 
> I can't reproduce your issue. You might have had connectivity issues to
> github
> 
>  editablefields cloned from https://github.com/eduerp/editablefields.git.
> [ok]
> eduerp cloned from https://github.com/eduerp/eduerp.git. [ok]
> 
>  Try again and feedback
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eduerp/eduerp/issues/5#issuecomment-22442460
> .

## 

_EMMANUEL *_Joseph*\*  | *_Creative Director | *_Paedia Technologies*
Mobile: 234 8050602370 |  234 7037301412
info@paediatech.com | www.paediatech.com

_...we got I.T all covered!_

**Comment by komputa** [comment]
![eduerp](https://f.cloud.github.com/assets/3993583/942846/0d9830b0-01d9-11e3-8a3c-cf519cd962b5.JPG)

I get the attached error and after some few clicks, it will take my mysql

down (and the site will go offline) which I have to restart (service
apache2 restart > service mysql start) before it will come up again.

(At that point all websites using the same mysql installation on the server
will now be able to connect to it

I dont know how to correct this.

**Comment by alanbarrett** [comment]
I have no idea why MySQL is taken down... as it is a separate server it
should be robust against any user error... So I do not know why it would
stop.

On the specific error message you got. That is because the content type
(CCK) 'course_instance' is missing from the instalation. That is likely
because the student module did not complete instalation properly. This
could be because you had a slow server or connectivity problems when you
were installing and something timed out.

The best thing to do would be to install again when connectivity is better
and try again. It is possible to install any missing content types by
hand... but before doing that it would be better to try a clean install
again. I hope this helps. If you still have problems, let us know.

We have noticed a few people having trouble with installation when the
infrastructure is not ideal but install has always worked with a good
infrastructure.

```
Alan.
```

**Comment by komputa** [comment]
Thank you so much for you reply.

I will setup on another server.

I have a merchant account with interswitch (for student payment) but I dont know how to integrate with it the platform, any help?

Regards

**Comment by kodion** [comment]
EduPAY integrates the Interswitch platform to EduERP providing payment that integrates a chip based ID card.   

It is straightforward to switch over.   Ask your Interswitch account managers or send e-mail to eduerp@datasphir.com when you are ready

**Comment by komputa** [comment]
Emmanuel Joseph sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/f166da41-dd35-4f6d-b0b1-2707e7227f5a

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Unsubscribe: https://twitter.com/i/o?t=1&iid=c21232879caa448abb9e222fa3361e55&uid=0&c=IuVwbCB3dgHrNGkmc3URyskbF1CMWa3WbGIV23uahLKHb4vXDcr9cC%2FN6rbpwhQixLwSqF2bMGCszoyZRTizlhsWpi6tJiiG3WJJeM8jMiYmyZKLAi3R3g%3D%3D&nid=9+26

Need help?
https://support.twitter.com
