### ISSUE TITLE
is upgrading to Drupal 7 possible?

### ISSUE THREAD

**Issue by komputa** [eduerp/eduerp#6]
Great job @ahoyi @alanbarrett @kodion @takinbo and all @DataSphir crew with this app!

I want to use a module in my quest to develop and android/iOS app for the wonderfull software but the minimum drupal is 7 has been depreciated. 

When can we have the updated drupal 7 version of the software or what can I do to upgrade it to drupal 7?

Best Regards

**Comment by kodion** [comment]
We will probably be going straight to v8 at this rate but the current focus is on helping institutions use what's currently available and serves their purpose quite well.   Please keep the user group updated with any progress you make in this direction
