### ISSUE TITLE
Help in Zimbra Configurations.

### ISSUE THREAD

**Issue by komputa** [eduerp/eduerp#7]
Hi everyone,

I am having challenges wrapping my head around the zimbra settings in the admin.
1. SOAP URL: (I dont know what to put here) since all the downloads were done automatically by the make file.
2. Name (Zimbra adminisration user name.): I am just setting this up or must I supposed to have registered an account with zimbra?

Dont know what to put
1. Password(Zimbra adminisration password.): Same as 2 above.

**Comment by alanbarrett** [comment]
These are only useful if you have your own Zimbra server installed in the
university for handing the University e-mail. If you do not, you should
disable the Zimbra module.

If you have set up a Zimbra server the URL is like this
https://your.site.name:7071/service/admin/soap/ but should be described in
the Zimbra doc.

```
Alan.
```
