### ISSUE TITLE
Courses not showing up on students portal.

### ISSUE THREAD

**Issue by komputa** [eduerp/eduerp#8]
Hello once again.

I setup faculty/department/semester/programmes and all that.

I also created a course for the semester and an attached a lecturer to it

I applied as a student and grant my admission and applied scholarship to that student. But trying course registration at the student end will just display the maximum/minimum credits and indicates that there are no courses available to be registered (even after I have added up to four courses to that programme/semester)
![course error](https://f.cloud.github.com/assets/3993583/1142828/f01d9446-1cf7-11e3-9826-ed827f4754bc.JPG)

![course3](https://f.cloud.github.com/assets/3993583/1142838/353c7d84-1cf9-11e3-9311-ad23381fb832.JPG)

Also Mr @alanbarrett  , is it possible for me allow students to register for both semesters once (at the beginning of first sem.). and if a student fails a course (in 100Level for example), the course will come up first as part of courses in 200 level at the point of registering ?

Help will be highly appreciated!

**Comment by kodion** [comment]
These are support requests not EduERP issues to track.  Community support is offered in the user group - http://lists.eko-konnect.org.ng/cgi-bin/mailman/listinfo/eduerp-users

**Comment by komputa** [comment]
Ok. thanks sir
